GET http://localhost:5000/users HTTP/1.1
###
GET http://localhost:5000/users/ismaeelakram HTTP/1.1
###
POST http://localhost:5000/auth HTTP/1.1
content-type: application/json

{"username": "ismaeelakram", "password": "password123"}